var removeDiacritics = require('../').remove,
    assert = require('assert');

assert.strictEqual(removeDiacritics("Iлｔèｒｎåｔïｏｎɑｌíƶａｔï߀ԉ"),
    "Internationalizati0n");
assert.strictEqual(removeDiacritics("Båｃòл íｐѕùｍ ðｏɭ߀ｒ ѕïｔ ａϻèｔ âùþê ａԉᏧ߀üïｌɭê ƃëéｆ ｃｕｌρá ｆïｌèｔ ϻｉǥｎòｎ ｃｕρｉᏧａｔａｔ ｕｔ êлｉｍ ｔòлɢùê."),
    "Bacon ipѕum dhol0r ѕit aMet authe and0uille beef culpa filet Mignon cupidatat ut enim tonGue.");
assert.strictEqual(removeDiacritics("ᴎᴑᴅᴇȷʂ"), "NoDEJs");

assert.strictEqual(removeDiacritics("hambúrguer"), "hamburguer");
assert.strictEqual(removeDiacritics("hŒllœ"), "hOElloe");
assert.strictEqual(removeDiacritics("Fußball"), "Fussball");

assert.strictEqual(removeDiacritics("ABCDEFGHIJKLMNOPQRSTUVWXYZé"), "ABCDEFGHIJKLMNOPQRSTUVWXYZe");

var test = [
  ["&#225;","á","a acuta","A"  ],
  ["&#192;","À","A grave","A"  ],
  ["&#224;","à","a grave","A"  ],
  ["&#194;","Â","A circonflessa","A"  ],
  ["&#226;","â","a circonflessa","A"  ],
  ["&#196;","Ä","A dieresi","AE"  ],
  ["&#228;","ä","a dieresi","AE"  ],
  ["&#258;","Ă","A breve","A"  ],
  ["&#259;","ă","a breve","A"  ],
  ["&#256;","Ā","A linea","A"  ],
  ["&#257;","ā","a linea","A"  ],
  ["&#195;","Ã","A tilde","A"  ],
  ["&#227;","ã","a tilde","A"  ],
  ["&#197;","Å","A tondo","AA"  ],
  ["&#229;","å","a tondo","AA"  ],
  ["&#260;","Ą","A ogonek","A"  ],
  ["&#261;","ą","a ogonek","A"  ],
  ["&#198;","Æ","Insieme AE","AE"  ],
  ["&#230;","æ","Insieme ae","AE"  ],
  ["&#262;","Ć","C acuta","C"  ],
  ["&#263;","ć","c acuta","C"  ],
  ["&#266;","Ċ","C punto","C"  ],
  ["&#267;","ċ","c punto","C"  ],
  ["&#264;","Ĉ","C circonflessa","C"  ],
  ["&#265;","ĉ","c circonflessa","C"  ],
  ["&#268;","Č","C caron","C"  ],
  ["&#269;","č","c caron","C"  ],
  ["&#199;","Ç","C cedilla","C"  ],
  ["&#231;","ç","c cedilla","C"  ],
  ["&#270;","Ď","D caron","D"  ],
  ["&#271;","ď","d caron","D"  ],
  ["&#272;","Đ","Eth","D"  ],
  ["&#273;","đ","Eth","D"  ],
  ["&#208;","Ð","Eth","D"  ],
  ["&#393;","Ɖ","Eth","D"  ],
  ["&#201;","É","E acuta","E"  ],
  ["&#233;","é","e acuta","E"  ],
  ["&#200;","È","E grave","E"  ],
  ["&#232;","è","e grave","E"  ],
  ["&#278;","Ė","E punto","E"  ],
  ["&#279;","ė","e punto","E"  ],
  ["&#202;","Ê","E circonflessa","E"  ],
  ["&#234;","ê","e circonflessa","E"  ],
  ["&#203;","Ë","E dieresi","E"  ],
  ["&#235;","ë","e dieresi","E"  ],
  ["&#282;","Ě","E caron","E"  ],
  ["&#283;","ě","e caron","E"  ],
  ["&#276;","Ĕ","E breve","E"  ],
  ["&#277;","ĕ","e breve","E"  ],
  ["&#274;","Ē","E linea","E"  ],
  ["&#275;","ē","e linea","E"  ],
  ["&#280;","Ę","E ogonek","E"  ],
  ["&#281;","ę","e ogonek","E"  ],
  ["&#288;","Ġ","G punto","G"  ],
  ["&#289;","ġ","g punto","G"  ],
  ["&#284;","Ĝ","G circonflessa","G"  ],
  ["&#285;","ĝ","g circonflessa","G"  ],
  ["&#286;","Ğ","G breve","G"  ],
  ["&#287;","ğ","g breve","G"  ],
  ["&#290;","Ģ","G cedilla","G"  ],
  ["&#291;","ģ","g cedilla","G"  ],
  ["&#292;","Ĥ","H circonflessa","H"  ],
  ["&#293;","ĥ","h circonflessa","H"  ],
  ["&#294;","Ħ","H barra","H"  ],
  ["&#295;","ħ","h barra","H"  ],
  ["&#73;","I","I senza punto","I"  ],
  ["&#305;","i","i punto","I"  ],
  ["&#105;","ı","i senza punto","I"  ],
  ["&#205;","Í","I acuta","I"  ],
  ["&#237;","í","i acuta","I"  ],
  ["&#204;","Ì","I grave","I"  ],
  ["&#236;","ì","i grave","I"  ],
  ["&#304;","İ","I punto","I"  ],
  ["&#206;","Î","I circonflessa","I"  ],
  ["&#238;","î","i circonflessa","I"  ],
  ["&#207;","Ï","I dieresi","I"  ],
  ["&#239;","ï","i dieresi","I"  ],
  ["&#300;","Ĭ","I breve","I"  ],
  ["&#301;","ĭ","i breve","I"  ],
  ["&#298;","Ī","I linea","I"  ],
  ["&#299;","ī","i linea","I"  ],
  ["&#296;","Ĩ","I tilde","I"  ],
  ["&#297;","ĩ","i tilde","I"  ],
  ["&#302;","Į","I ogonek","I"  ],
  ["&#303;","į","i ogonek","I"  ],
  ["&#306;","Ĳ","Insieme IJ","IJ"  ],
  ["&#307;","ĳ","Insieme ij","IJ"  ],
  ["&#308;","Ĵ","J circonflessa","J"  ],
  ["&#309;","ĵ","j circonflessa","J"  ],
  ["&#310;","Ķ","K cedilla","K"  ],
  ["&#311;","ķ","k cedilla","K"  ],
  ["&#313;","Ĺ","L acuta","L"  ],
  ["&#314;","ĺ","l acuta","L"  ],
  ["&#319;","Ŀ","L punto","L"  ],
  ["&#320;","ŀ","l punto","L"  ],
  ["&#317;","Ľ","L caron","L"  ],
  ["&#318;","ľ","l caron","L"  ],
  ["&#315;","Ļ","L cedilla","L"  ],
  ["&#316;","ļ","l cedilla","L"  ],
  ["&#321;","Ł","L barra traversa","L"  ],
  ["&#322;","ł","l barra traversa","L"  ],
  ["&#323;","Ń","N acuta","N"  ],
  ["&#324;","ń","n acuta","N"  ],
  ["&#327;","Ň","N caron","N"  ],
  ["&#328;","ň","n caron","N"  ],
  ["&#209;","Ñ","N tilde","N"  ],
  ["&#241;","ñ","n tilde","N"  ],
  ["&#325;","Ņ","N cedilla","N"  ],
  ["&#326;","ņ","n cedilla","N"  ],
  ["&#329;","ʼn","Eng","N"  ],
  ["&#331;","ŋ","Eng","N"  ],
  ["&#211;","Ó","O acuta","O"  ],
  ["&#243;","ó","o acuta","O"  ],
  ["&#210;","Ò","O grave","O"  ],
  ["&#242;","ò","o grave","O"  ],
  ["&#212;","Ô","O circonflessa","O"  ],
  ["&#244;","ô","o circonflessa","O"  ],
  ["&#214;","Ö","O dieresi","OE"  ],
  ["&#246;","ö","o dieresi","OE"  ],
  ["&#334;","Ŏ","O breve","O"  ],
  ["&#335;","ŏ","o breve","O"  ],
  ["&#332;","Ō","O linea","O"  ],
  ["&#333;","ō","o linea","O"  ],
  ["&#213;","Õ","O tilde","O"  ],
  ["&#245;","õ","o tilde","O"  ],
  ["&#336;","Ő","O doppia acuta","O"  ],
  ["&#337;","ő","o doppia acuta","O"  ],
  ["&#216;","Ø","O barra","OE"  ],
  ["&#248;","ø","o barra","OE"  ],
  ["&#140;","Œ","Insieme OE","OE"  ],
  ["&#156;","œ","Insieme oe","OE"  ],
  ["&#338;","Œ","Insieme OE","OE"  ],
  ["&#339;","œ","Insieme oe","OE"  ],
  ["&#340;","Ŕ","R acuta","R"  ],
  ["&#341;","ŕ","r acuta","R"  ],
  ["&#344;","Ř","R caron","R"  ],
  ["&#345;","ř","r caron","R"  ],
  ["&#342;","Ŗ","R cedilla","R"  ],
  ["&#343;","ŗ","r cedilla","R"  ],
  ["&#346;","Ś","S acuta","S"  ],
  ["&#347;","ś","s acuta","S"  ],
  ["&#348;","Ŝ","S circonflessa","S"  ],
  ["&#349;","ŝ","s circonflessa","S"  ],
  ["&#138;","Š","S caron","S"  ],
  ["&#154;","š","s caron","S"  ],
  ["&#352;","Š","S caron","S"  ],
  ["&#353;","š","s caron","S"  ],
  ["&#350;","Ş","S cedilla","S"  ],
  ["&#351;","ş","s cedilla","S"  ],
  ["&#223;","ß","Doppia s","SS"  ],
  ["&#356;","Ť","T caron","T"  ],
  ["&#357;","ť","t caron","T"  ],
  ["&#354;","Ţ","T cedilla","T"  ],
  ["&#355;","ţ","t cedilla","T"  ],
  ["&#222;","Þ","Thorn","TH"  ],
  ["&#254;","þ","Thorn","TH"  ],
  ["&#358;","Ŧ","T barra","T"  ],
  ["&#359;","ŧ","t barra","T"  ],
  ["&#218;","Ú","U acuta","U"  ],
  ["&#250;","ú","u acuta","U"  ],
  ["&#217;","Ù","U grave","U"  ],
  ["&#249;","ù","u grave","U"  ],
  ["&#219;","Û","U circonflessa","U"  ],
  ["&#251;","û","u circonflessa","U"  ],
  ["&#220;","Ü","U dieresi","UE"  ],
  ["&#252;","ü","u dieresi","UE"  ],
  ["&#364;","Ŭ","U breve","U"  ],
  ["&#365;","ŭ","u breve","U"  ],
  ["&#362;","Ū","U linea","U"  ],
  ["&#363;","ū","u linea","U"  ],
  ["&#360;","Ũ","U tilde","U"  ],
  ["&#361;","ũ","u tilde","U"  ],
  ["&#366;","Ů","U tondo","U"  ],
  ["&#367;","ů","u tondo","U"  ],
  ["&#370;","Ų","U ogonek","U"  ],
  ["&#371;","ų","u ogonek","U"  ],
  ["&#368;","Ű","U doppia acuta","U"  ],
  ["&#369;","ű","u doppia acuta","U"  ],
  ["&#372;","Ŵ","W circonflessa","W"  ],
  ["&#373;","ŵ","w circonflessa","W"  ],
  ["&#221;","Ý","Y acuta","Y"  ],
  ["&#253;","ý","y acuta","Y"  ],
  ["&#374;","Ŷ","Y circonflessa","Y"  ],
  ["&#375;","ŷ","y circonflessa","Y"  ],
  ["&#159;","Ÿ","Y dieresi","Y"  ],
  ["&#255;","ÿ","y dieresi","Y"  ],
  ["&#376;","Ÿ","Y dieresi","Y"  ],
  ["&#377;","Ź","Z acuta","Z"  ],
  ["&#378;","ź","z acuta","Z"  ],
  ["&#379;","Ż","Z punto","Z"  ],
  ["&#380;","ż","z punto","Z"  ],
  ["&#142;","Ž","Z caron","Z"  ],
  ["&#158;","ž","z caron","Z"  ],
  ["&#381;","Ž","Z caron","Z"  ],
  ["&#382;","ž","z caron","Z"  ],
  ["&#192;","À","A grave","A'"  ],
  ["&#224;","à","a grave","A'"  ],
  ["&#200;","È","E grave","E'"  ],
  ["&#232;","è","e grave","E'"  ],
  ["&#204;","Ì","I grave","I'"  ],
  ["&#236;","ì","i grave","I'"  ],
  ["&#210;","Ò","O grave","O'"  ],
  ["&#242;","ò","o grave","O'"  ],
  ["&#217;","Ù","U grave","U'"  ],
  ["&#249;","ù","u grave","U'"  ]
];

test.forEach(function (t, i) {
	//console.log('Testing ' + t + ' [' + i + ']');
	
	var converted = removeDiacritics(t[1]);
	converted = converted.toUpperCase();
	console.log(t[1] + ' gets converted to  ' + converted + ', document says ' + t[3]);
});
